#ifndef DRIVER_INPUT_H
#define DRIVER_INPUT_H

#define INPUT_MOUSE_PICKING_CLICK 1
#define INPUT_MOUSE_PICKING_DRAG 1

#define INPUT_MOUSE_ARCBALL_ROTATE 1
#define INPUT_MOUSE_ARCBALL_TRANSLATE 3

#define INPUT_MOUSE_SIDEVIEW_TRANSLATE 3

#endif
